import 'package:gmail/components/email.dart';

class Emailrepository {
  static final List<Email> listemail = [
    Email(
      "Facebook",
      "Você tem novas notificações",
      "3 novas curtidas e 2 comentários",
      DateTime.parse("2025-05-25"),
      true,
      false,
    ),
    Email(
      "YouTube",
      "Novo vídeo de Canal XYZ",
      "Veja agora: 'Como programar em Kotlin'",
      DateTime.parse("2025-05-24"),
      true,
      true,
    ),
    Email(
      "Gmail",
      "Verificação de segurança",
      "Novo login detectado em seu dispositivo",
      DateTime.parse("2025-05-23"),
      false,
      false,
    ),
    Email(
      "LinkedIn",
      "Vagas recomendadas para você",
      "Veja as novas oportunidades da semana",
      DateTime.parse("2025-05-22"),
      true,
      false,
    ),
    Email(
      "Instagram",
      "Você tem novas mensagens",
      "3 pessoas enviaram mensagens para você",
      DateTime.parse("2025-05-25"),
      true,
      true,
    ),
    Email(
      "Netflix",
      "Novidades no catálogo",
      "Confira os lançamentos deste mês",
      DateTime.parse("2025-05-21"),
      false,
      true,
    ),
    Email(
      "Spotify",
      "Sua retrospectiva 2025 chegou!",
      "Veja quais músicas você mais ouviu",
      DateTime.parse("2025-05-20"),
      true,
      false,
    ),
    Email(
      "Amazon",
      "Seu pedido foi enviado",
      "Seu pedido #123456 foi despachado",
      DateTime.parse("2025-05-24"),
      false,
      true,
    ),
    Email(
      "Uber",
      "Resumo da sua semana",
      "Você fez 3 viagens com a Uber",
      DateTime.parse("2025-05-23"),
      true,
      false,
    ),
    Email(
      "iFood",
      "Cupom exclusivo para você",
      "Ganhe R\$15 de desconto no próximo pedido",
      DateTime.parse("2025-05-22"),
      true,
      true,
    ),
    Email(
      "Twitter",
      "Novos seguidores",
      "2 pessoas começaram a seguir você",
      DateTime.parse("2025-05-21"),
      false,
      false,
    ),
    Email(
      "Zoom",
      "Reunião agendada",
      "Sua reunião começa em 30 minutos",
      DateTime.parse("2025-05-25"),
      true,
      false,
    ),
    Email(
      "Google",
      "Atividade recente na sua conta",
      "Veja detalhes de acessos recentes",
      DateTime.parse("2025-05-20"),
      false,
      false,
    ),
    Email(
      "Dropbox",
      "Seu espaço está acabando",
      "Faltam apenas 500MB de espaço",
      DateTime.parse("2025-05-18"),
      true,
      false,
    ),
    Email(
      "GitHub",
      "Novo pull request",
      "Você recebeu um novo PR no repositório",
      DateTime.parse("2025-05-17"),
      false,
      true,
    ),
    Email(
      "Outlook",
      "Organize sua caixa de entrada",
      "Dicas para limpar seus emails antigos",
      DateTime.parse("2025-05-19"),
      true,
      false,
    ),
    Email(
      "Microsoft",
      "Atualização disponível",
      "Atualize seu Windows para a versão mais recente",
      DateTime.parse("2025-05-16"),
      false,
      true,
    ),
    Email(
      "Steam",
      "Promoção de jogos",
      "Descontos de até 90% no Festival de Inverno",
      DateTime.parse("2025-05-25"),
      true,
      true,
    ),
    Email(
      "Apple",
      "Sua assinatura será renovada",
      "Apple Music será renovada em 3 dias",
      DateTime.parse("2025-05-23"),
      true,
      false,
    ),
    Email(
      "Coursera",
      "Novo curso recomendado",
      "Explore: Inteligência Artificial Aplicada",
      DateTime.parse("2025-05-24"),
      true,
      true,
    ),
  ];
}
